services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sonha
      POSTGRES_PASSWORD: sonha
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
