// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"
)

type Todo struct {
	ID        int64
	Title     string
	IsDone    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
